# Generated by Django 3.2.11 on 2022-01-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celery_monitor", "0002_workerstate_last_update"),
        ("cabotapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuscheck",
            name="target_workers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Worker which should execute the test.",
                to="celery_monitor.WorkerState",
            ),
        ),
        migrations.AddField(
            model_name="statuscheckresult",
            name="worker",
            field=models.TextField(null=True),
        ),
    ]
