# Generated by Django 3.2.11 on 2022-01-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_monitor', '0002_workerstate_last_update'),
        ('cabotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheck',
            name='target_worker',
            field=models.ManyToManyField(blank=True, help_text='Worker which should execute the test.', to='celery_monitor.WorkerState'),
        ),
    ]
