# Generated by Django 3.2.11 on 2022-01-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0002_statuscheck_target_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuscheck',
            old_name='target_worker',
            new_name='target_workers',
        ),
        migrations.AddField(
            model_name='statuscheckresult',
            name='worker',
            field=models.TextField(null=True),
        ),
    ]
